import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Sparkles,MapPin,CalendarDays,Clock3,ArrowRight,ChevronLeft,ShieldCheck,Star,Orbit,Search,Download,RefreshCw,ChevronDown} from 'lucide-react';
import './style.css';
const API='/api';
const nav=[['home','હોમ'],['kundli','કુંડળી'],['panchang','પંચાંગ'],['about','અમારા વિશે']];
function App(){
 const [page,setPage]=useState('home'),[result,setResult]=useState(null),[form,setForm]=useState({name:'',dob:'',tob:'',place:'',latitude:'',longitude:'',timezone:''});
 const [suggestions,setSuggestions]=useState([]),[loadingPlace,setLoadingPlace]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''); const timer=useRef();
 const update=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
 const search=v=>{setForm(f=>({...f,place:v,latitude:'',longitude:'',timezone:''}));setSuggestions([]);clearTimeout(timer.current);if(v.trim().length<2){setLoadingPlace(false);return}setLoadingPlace(true);timer.current=setTimeout(async()=>{try{const r=await fetch(`${API}/places/?q=${encodeURIComponent(v.trim())}`);const j=await r.json();setSuggestions(j.results||[])}catch{setSuggestions([])}finally{setLoadingPlace(false)}},300)};
 const choose=x=>{setForm(f=>({...f,place:x.label,latitude:x.lat,longitude:x.lon,timezone:x.timezone}));setSuggestions([])};
 async function submit(e){e.preventDefault();setError('');if(!form.latitude){setError('કૃપા કરીને શોધમાંથી સાચું જન્મ સ્થળ પસંદ કરો.');return}setLoading(true);try{const r=await fetch(`${API}/kundli/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!j.ok)throw Error(j.error);setResult(j);setPage('kundli')}catch(e){setError('કુંડળી ગણવામાં સમસ્યા આવી. જન્મ વિગતો તપાસીને ફરી પ્રયાસ કરો.')}finally{setLoading(false)}}
 return <div className="app"><header><button className="logo" onClick={()=>setPage('home')}><span>✦</span> તારક</button><nav>{nav.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><button className="outline" onClick={()=>{setPage('home');setTimeout(()=>document.getElementById('birth')?.scrollIntoView({behavior:'smooth'}),50)}}>કુંડળી બનાવો <ArrowRight size={15}/></button></header>
 {page==='home'&&<Home form={form} update={update} search={search} choose={choose} suggestions={suggestions} loadingPlace={loadingPlace} error={error} loading={loading} submit={submit}/>}
 {page==='kundli'&&result?<Result data={result} back={()=>setPage('home')}/>:page==='kundli'&&!result?<Home form={form} update={update} search={search} choose={choose} suggestions={suggestions} loadingPlace={loadingPlace} error={error} loading={loading} submit={submit}/>:null}
 {page==='panchang'&&<Info title="આજનું પંચાંગ" text="પંચાંગ મોડ્યુલ માટે સ્થાન આધારિત તિથિ, વાર, નક્ષત્ર, યોગ, કરણ, સૂર્યોદય અને સૂર્યાસ્તનું એન્જિન તૈયાર છે. જન્મકુંડળીમાં પંચાંગ ડેટા પણ સ્થાન અને સમય ઝોનથી ગણાય છે."/>}
 {page==='about'&&<Info title="તારક વિશે" text="તારકનો હેતુ વૈદિક જ્યોતિષની પરંપરાગત ગણતરીને પારદર્શક, આધુનિક અને Gujarati-first અનુભવમાં રજૂ કરવાનો છે. ગ્રહોની સ્થિતિ astronomical ephemeris પરથી ગણાય છે; અર્થઘટનને નિશ્ચિત વૈજ્ઞાનિક આગાહી તરીકે રજૂ કરવામાં આવતું નથી."/>}
 <footer><div>તારક</div><span>વૈદિક કુંડળી · Lahiri Sidereal · Swiss Ephemeris</span><span>મૂળભૂત કુંડળી મફત</span></footer></div>
}
function Home({form,update,search,choose,suggestions,loadingPlace,error,loading,submit}){return <main><section className="hero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> વૈદિક જ્યોતિષ · આધુનિક અનુભવ</div><h1>તમારા તારાઓને<br/><em>સમજો.</em></h1><p>જન્મ તારીખ, ચોક્કસ સમય અને સાચા જન્મ સ્થળ પરથી તમારી ગુજરાતી વૈદિક જન્મકુંડળી મેળવો.</p><div className="trust"><span><ShieldCheck size={17}/> ચોક્કસ astronomical ગણતરી</span><span><Star size={17}/> મૂળભૂત કુંડળી મફત</span></div></div>
 <section id="birth" className="card formCard"><div className="cardHead"><div><span className="mini">FREE KUNDLI</span><h2>જન્મ વિગતો</h2><p>ચોકસાઈ માટે દરેક માહિતી સાચી પસંદ કરો.</p></div><Orbit/></div><form onSubmit={submit}><label>નામ<input name="name" value={form.name} onChange={update} placeholder="જેમ કે: હર્ષ પટેલ" required/></label><div className="grid2"><label>જન્મ તારીખ<div className="withIcon"><CalendarDays/><input type="date" name="dob" value={form.dob} onChange={update} required/></div></label><label>જન્મ સમય<div className="withIcon"><Clock3/><input type="time" name="tob" value={form.tob} onChange={update} required/></div></label></div><label>જન્મ સ્થળ<div className="withIcon"><MapPin/><input value={form.place} onChange={e=>search(e.target.value)} placeholder="શહેર, જિલ્લો અથવા દેશ શોધો" autoComplete="off" required/></div>{loadingPlace&&<div className="dropdown">સ્થળો શોધી રહ્યા છીએ…</div>}{!loadingPlace&&suggestions.length>0&&<div className="dropdown">{suggestions.map((x,i)=><button type="button" key={i} onClick={()=>choose(x)}><MapPin size={15}/><span><b>{x.city}</b><small>{x.state?x.state+', ':''}{x.country} · {x.timezone}</small></span></button>)}</div>}</label>{form.latitude&&<div className="selected">✓ {form.place}<span>{Number(form.latitude).toFixed(4)}, {Number(form.longitude).toFixed(4)} · {form.timezone}</span></div>}{error&&<div className="error">{error}</div>}<button className="primary" disabled={loading}>{loading?'કુંડળી ગણાઈ રહી છે…':<>મારી કુંડળી બનાવો <ArrowRight size={18}/></>}</button></form><div className="method"><span>Calculation</span><b>Vedic / Sidereal · Lahiri</b><span>Engine</span><b>Swiss Ephemeris</b></div></section></section>
 <section className="featureRow"><Feature n="01" t="Real planetary data" d="ગ્રહોની સ્થિતિ astronomical ephemeris પરથી ગણાય છે — mock values નહીં."/><Feature n="02" t="ચોક્કસ સ્થળ" d="શહેર સાથે latitude, longitude અને timezone પણ પસંદ થાય છે."/><Feature n="03" t="Gujarati-first" d="નક્ષત્ર, રાશિ, ભાવ, દશા અને પરિણામો સરળ Gujarati UIમાં."/></section>
 <section className="trustBand"><div><span>TRANSPARENT METHOD</span><h2>ગણતરી અને અર્થઘટન અલગ રાખીએ છીએ.</h2></div><p>Planetary positions engine દ્વારા ગણાય છે. પરંપરાગત જ્યોતિષીય અર્થઘટન અલગ સ્તરે રજૂ થાય છે, જેથી calculation data સ્પષ્ટ રહે.</p></section></main>}
function Feature({n,t,d}){return <div><span className="num">{n}</span><h3>{t}</h3><p>{d}</p></div>}
function Info({title,text}){return <main className="info"><div className="eyebrow"><Sparkles size={15}/> તારક</div><h1>{title}</h1><p>{text}</p></main>}
function Result({data,back}){const k=data.kundli; return <main className="result"><button className="back" onClick={back}><ChevronLeft size={16}/> ફરીથી કુંડળી બનાવો</button><div className="resultTop"><div><div className="eyebrow"><Sparkles size={15}/> તમારી જન્મકુંડળી</div><h1>{data.name}, તમારું આકાશ.</h1><p>{data.place} · {k.location.timezone}</p></div><button className="outline" onClick={()=>window.print()}><Download size={15}/> Print / PDF</button></div><div className="metrics"><Metric t="લગ્ન" v={`${k.lagna} · ${k.lagna_degree}°`}/><Metric t="ચંદ્ર રાશિ" v={k.moon_rashi}/><Metric t="જન્મ નક્ષત્ર" v={`${k.janma_nakshatra} · પાદ ${k.nakshatra_pada}`}/><Metric t="સૂર્ય રાશિ" v={k.sun_rashi}/><Metric t="અયનાંશ" v={`${k.ayanamsha}°`}/></div><section className="resultGrid"><KundliChart k={k}/><div className="card planetCard"><div className="sectionTitle"><span>PLANETS</span><h2>ગ્રહ સ્થિતિ</h2></div>{k.planets.map(p=><div className="planetRow" key={p.name}><b>{p.name}</b><span>{p.rashi} · {p.degree.toFixed(2)}° · ભાવ {p.house}{p.retrograde?' · ℞':''}</span></div>)}</div></section><section className="card details"><div className="sectionTitle"><span>12 BHAVA</span><h2>ભાવ અને રાશિ</h2></div><div className="houseGrid">{k.houses.map(h=><div key={h.house}><small>{h.house}મો ભાવ</small><b>{h.rashi}</b><span>સ્વામી · {h.lord}</span></div>)}</div></section><section className="split"><section className="card"><div className="sectionTitle"><span>NAKSHATRA</span><h2>જન્મ નક્ષત્ર</h2></div><div className="bigValue">{k.janma_nakshatra}</div><p>પાદ {k.nakshatra_pada} · નક્ષત્ર સ્વામી {k.nakshatra_lord}</p></section><section className="card"><div className="sectionTitle"><span>DASHA</span><h2>વિમ્શોત્તરી દશા</h2></div><p>વર્તમાન મહાદશા</p><div className="bigValue small">{k.dasha.current_mahadasa.lord}</div><p>Antardasha · {k.dasha.current_antardasha.lord}</p></section></section><section className="card"><div className="sectionTitle"><span>NAVAMSHA · D9</span><h2>નવાંશ</h2></div><div className="navGrid">{k.navamsa.planets.map(p=><span key={p.name}><b>{p.name}</b>{p.rashi}</span>)}</div></section><div className="notice">ગણતરી: Vedic / Sidereal · Lahiri Ayanamsha · Swiss Ephemeris. જ્યોતિષીય અર્થઘટન પરંપરાગત દૃષ્ટિકોણ છે અને તેને વૈજ્ઞાનિક, તબીબી અથવા નાણાકીય નિશ્ચિતતા તરીકે ન લો.</div></main>}
function Metric({t,v}){return <div><span>{t}</span><b>{v}</b></div>}
function KundliChart({k}){const groups=Array.from({length:12},()=>[]);k.planets.forEach(p=>groups[(p.house||1)-1].push(p.name));const pos=['s1','s2','s3','s4','s5','s6','s7','s8','s9','s10','s11','s12'];return <div className="card chartCard"><div className="sectionTitle"><span>NORTH INDIAN STYLE</span><h2>જન્મ કુંડળી</h2></div><div className="chart"><div className="diamond d1"></div><div className="diamond d2"></div><div className="chartLagna">લગ્ન<br/><b>{k.lagna}</b></div>{groups.map((g,i)=><div className={`houseSlot ${pos[i]}`} key={i}><small>{i+1}</small>{g.map(n=><b key={n}>{n}</b>)}</div>)}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
